spring.application.name=game-engine
management.endpoints.web.exposure.exclude=health,info
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=game-engine

coach.name = mickey
team.name = mouse club

#change server port

server.port=7070

#application context path

#server.servlet.context-path=/game-enginei

# --- DATABASE CONFIGURATION START ---
# Tell Java where to find the MySQL container on port 3306
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/student_tracker?useSSL=false&serverTimezone=UTC
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.main.banner-mode=off
# Hibernate / JPA Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# --- DATABASE CONFIGURATION END ---